/**
 * resumeTemplate.js
 * -----------------------------------------------------------------------
 * Renders a structured resume JSON into HTML that visually matches the
 * Jake's-Resume-derived LaTeX template (airforceblue rule headers, tight
 * spacing, single-column ATS-safe layout).
 *
 * Deliberately NOT generated by an LLM per-request — the design must stay
 * identical across every tailored resume, so it's a fixed template that
 * only content flows through.
 * -----------------------------------------------------------------------
 */

// ---- design tokens pulled directly from the .tex source -----------------
const COLORS = {
  airforceblue: "#5C8AA8", // rgb(0.36, 0.54, 0.66) from the LaTeX color def
  darktext: "#1F2937",
  subtext: "#374151",
};

// Helvetica-first stack: matches your other resume variants and is one of
// the safest fonts for ATS text-extraction (no ligature/kerning weirdness).
const FONT_STACK =
  "'Helvetica Neue', Helvetica, Arial, 'Liberation Sans', sans-serif";

function escapeHtml(str = "") {
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// Bold-run helper so content can mark **like this** for emphasis (kept out
// of Gemini's hands as raw HTML — it only ever emits plain text + this
// lightweight markdown-ish bold syntax, which we escape-then-restore).
function inlineFormat(str = "") {
  const escaped = escapeHtml(str);
  return escaped.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
}

function contactLine(data) {
  const parts = [];
  if (data.phone)
    parts.push(
      `<a href="tel:${escapeHtml(data.phone)}">${escapeHtml(data.phone)}</a>`,
    );
  if (data.email)
    parts.push(
      `<a href="mailto:${escapeHtml(data.email)}">${escapeHtml(data.email)}</a>`,
    );
  if (data.portfolio)
    parts.push(
      `<a href="https://${escapeHtml(data.portfolio)}">${escapeHtml(data.portfolio)}</a>`,
    );
  return parts.join(' <span class="sep">&bull;</span> ');
}

function contactLine2(data) {
  const parts = [];
  if (data.linkedin)
    parts.push(
      `<a href="https://${escapeHtml(data.linkedin)}">${escapeHtml(data.linkedin)}</a>`,
    );
  if (data.github)
    parts.push(
      `<a href="https://${escapeHtml(data.github)}">${escapeHtml(data.github)}</a>`,
    );
  if (data.location) parts.push(escapeHtml(data.location));
  return parts.join(' <span class="sep">&bull;</span> ');
}

function highlightsLine(highlights = []) {
  if (!highlights.length) return "";
  return `<div class="highlights">${highlights
    .map((h) => escapeHtml(h))
    .join(' <span class="sep">&bull;</span> ')}</div>`;
}

function renderSkills(skills = []) {
  if (!skills.length) return "";
  const rows = skills
    .map(
      (group) =>
        `<div class="skill-row"><strong>${escapeHtml(group.category)}:</strong> ${escapeHtml(
          group.items.join(", "),
        )}</div>`,
    )
    .join("");
  return section("Technical Skills", `<div class="skills-block">${rows}</div>`);
}

function renderExperience(experience = []) {
  if (!experience.length) return "";
  const entries = experience
    .map(
      (job) => `
      <div class="entry">
        <div class="entry-header">
          <span class="entry-left"><strong>${escapeHtml(job.company)}</strong></span>
          <span class="entry-right">${escapeHtml(job.location)}</span>
        </div>
        <div class="entry-header entry-subrow">
          <span class="entry-left"><em>${escapeHtml(job.role)}</em></span>
          <span class="entry-right"><em>${escapeHtml(job.dates)}</em></span>
        </div>
        <ul class="bullets">
          ${(job.bullets || []).map((b) => `<li>${inlineFormat(b)}</li>`).join("")}
        </ul>
      </div>`,
    )
    .join("");
  return section("Work Experience", entries);
}

function renderProjects(projects = []) {
  if (!projects.length) return "";
  const items = projects
    .map(
      (p) =>
        `<li><strong>${escapeHtml(p.name)}</strong> &mdash; ${inlineFormat(p.description)}${
          p.link ? ` <a href="${escapeHtml(p.link)}">GitHub</a>` : ""
        }</li>`,
    )
    .join("");
  return section("Projects", `<ul class="bullets">${items}</ul>`);
}

function renderEducation(education = []) {
  if (!education.length) return "";
  const entries = education
    .map(
      (e) => `
      <div class="entry">
        <div class="entry-header">
          <span class="entry-left"><strong>${escapeHtml(e.school)}</strong></span>
          <span class="entry-right">${escapeHtml(e.location)}</span>
        </div>
        <div class="entry-header entry-subrow">
          <span class="entry-left"><em>${escapeHtml(e.degree)}</em></span>
          <span class="entry-right"><em>${escapeHtml(e.dates)}</em></span>
        </div>
      </div>`,
    )
    .join("");
  return section("Education", entries);
}

function renderSimpleList(title, items = []) {
  if (!items.length) return "";
  return section(
    title,
    `<ul class="bullets">${items.map((i) => `<li>${inlineFormat(i)}</li>`).join("")}</ul>`,
  );
}

function section(title, innerHtml) {
  return `
    <section>
      <h2>${escapeHtml(title)}</h2>
      ${innerHtml}
    </section>`;
}

/**
 * buildResumeHTML(data) -> full HTML document string
 *
 * data shape:
 * {
 *   name, title, phone, email, portfolio, linkedin, github, location,
 *   highlights: string[],
 *   summary: string,
 *   skills: [{ category, items: string[] }],
 *   experience: [{ company, location, role, dates, bullets: string[] }],
 *   projects: [{ name, description, link }],
 *   education: [{ school, location, degree, dates }],
 *   certifications: string[],
 *   additional: string[]
 * }
 */
function buildResumeHTML(data) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>${escapeHtml(data.name || "Resume")}</title>
<style>
  @page { size: A4; }
  * { box-sizing: border-box; }
  html, body { width: 100%; max-width: 100%; overflow-wrap: break-word; word-wrap: break-word; }
  body {
    font-family: ${FONT_STACK};
    color: ${COLORS.darktext};
    font-size: 9.8pt;
    line-height: 1.28;
    margin: 0;
  }
  a { color: ${COLORS.airforceblue}; text-decoration: none; }
  .sep { color: ${COLORS.subtext}; margin: 0 4px; }

  header { text-align: center; margin-bottom: 2px; }
  header h1 { font-size: 19pt; margin: 0 0 1px; letter-spacing: 0.2px; }
  header .role-title { font-style: italic; font-size: 11pt; margin: 0 0 2px; color: ${COLORS.subtext}; }
  .contact-line { font-size: 9pt; margin: 1px 0; }
  .highlights {
    font-size: 9pt;
    margin-top: 3px;
    padding-top: 2px;
  }

  section { margin-top: 8px; }
  h2 {
    font-size: 11.5pt;
    text-transform: uppercase;
    letter-spacing: 0.4px;
    color: ${COLORS.airforceblue};
    border-bottom: 1px solid ${COLORS.darktext};
    padding-bottom: 2px;
    margin: 0 0 5px;
    break-after: avoid;
  }

  .skill-row { font-size: 9.5pt; margin-bottom: 2px; }

  .entry { margin-bottom: 6px; }
  .entry-header {
    display: flex;
    justify-content: space-between;
    font-size: 10pt;
    break-after: avoid;
  }
  .entry-subrow { font-size: 9.5pt; color: ${COLORS.subtext}; break-after: avoid; }
  .entry-left { text-align: left; }
  .entry-right { text-align: right; white-space: nowrap; }

  ul.bullets { margin: 3px 0 0; padding-left: 14px; }
  ul.bullets li {
    margin-bottom: 3px;
    padding-left: 2px;
    break-inside: avoid;
    orphans: 2;
    widows: 2;
  }
  ul.bullets li:last-child { margin-bottom: 0; }
  ul.bullets li::marker { color: ${COLORS.airforceblue}; }

  .summary { font-size: 10.5pt; margin: 0; }
  strong { color: ${COLORS.darktext}; }
</style>
</head>
<body>
  <header>
    <h1>${escapeHtml(data.name)}</h1>
    <div class="role-title">${escapeHtml(data.title)}</div>
    <div class="contact-line">${contactLine(data)}</div>
    <div class="contact-line">${contactLine2(data)}</div>
    ${highlightsLine(data.highlights)}
  </header>

  ${data.summary ? section("Summary", `<p class="summary">${inlineFormat(data.summary)}</p>`) : ""}
  ${renderSkills(data.skills)}
  ${renderExperience(data.experience)}
  ${renderProjects(data.projects)}
  ${renderEducation(data.education)}
  ${renderSimpleList("Certifications & Coursework", data.certifications)}
  ${renderSimpleList("Additional Information", data.additional)}
</body>
</html>`;
}

export { buildResumeHTML, escapeHtml, inlineFormat };
